/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Pharamcy.Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int attempt=0;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLogin = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButlogin = new javax.swing.JButton();
        jButCancel = new javax.swing.JButton();
        jButExit = new javax.swing.JButton();
        jBDocter = new javax.swing.JButton();
        jBPharmacy = new javax.swing.JButton();
        jBPatient = new javax.swing.JButton();
        jBPayment = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBGPAppointment = new javax.swing.JButton();
        jBPharamcyffice = new javax.swing.JButton();
        jBSurgery = new javax.swing.JButton();
        jBHospital = new javax.swing.JButton();
        jBSpecialist = new javax.swing.JButton();
        jBConstant = new javax.swing.JButton();
        jBPharmacist = new javax.swing.JButton();
        jBHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 240, 40));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 240, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Login System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Login");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 40));

        jButlogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButlogin.setText("Login");
        jButlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButloginActionPerformed(evt);
            }
        });
        jPanel2.add(jButlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 230, 130, -1));

        jButCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButCancel.setText("Cancel");
        jButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 230, 130, -1));

        jButExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButExit.setText("Exit");
        jButExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButExitActionPerformed(evt);
            }
        });
        jPanel2.add(jButExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 230, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 650, 300));

        jBDocter.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBDocter.setText("Docter");
        getContentPane().add(jBDocter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 40));

        jBPharmacy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPharmacy.setText("Pharmacy");
        jBPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(jBPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, 40));

        jBPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPatient.setText("Patient");
        getContentPane().add(jBPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 250, 40));

        jBPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPayment.setText("Payment");
        jBPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(jBPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("Pharamcy Management Sysytem");
        jPanel3.add(jLabel4);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1070, 80));

        jBGPAppointment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBGPAppointment.setText("GPAppointment");
        getContentPane().add(jBGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 250, 40));

        jBPharamcyffice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPharamcyffice.setText("Pharmacy Office");
        getContentPane().add(jBPharamcyffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 250, 40));

        jBSurgery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSurgery.setText("Surgery");
        getContentPane().add(jBSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, 250, 40));

        jBHospital.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBHospital.setText("Hospital");
        getContentPane().add(jBHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 250, 40));

        jBSpecialist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSpecialist.setText("Specialist");
        getContentPane().add(jBSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 250, 40));

        jBConstant.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBConstant.setText("Consaltant");
        jBConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConstantActionPerformed(evt);
            }
        });
        getContentPane().add(jBConstant, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 250, 40));

        jBPharmacist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPharmacist.setText("Pharmacist");
        getContentPane().add(jBPharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 250, 40));

        jBHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBHelp.setText("Help");
        getContentPane().add(jBHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 570, 250, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jLoginActionPerformed
    private JFrame frame;
    private void jButExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm You want to Exit", "Pharmacy System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);
        System.exit(0);
    }//GEN-LAST:event_jButExitActionPerformed

    private void jButloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButloginActionPerformed
        // TODO add your handling code here:
        String Password = jPassword.getText();
        String Username = jLogin.getText();

        if (Username.contains("en17411486") && Password.contains("ln-vd789")) {
            jBDocter.setEnabled(true);
            jBConstant.setEnabled(true);
            jBDocter.setEnabled(true);
            jBHelp.setEnabled(true);
            jBHospital.setEnabled(true);
            jBPatient.setEnabled(true);
            jBPayment.setEnabled(true);
            jBPharamcyffice.setEnabled(true);
            jBPharmacist.setEnabled(true);
            jBPharmacy.setEnabled(true);
            jBSpecialist.setEnabled(true);
            jBSurgery.setEnabled(true);
            jBGPAppointment.setEnabled(true);

            jPanel2.hide();
            jPassword.hide();
            jLogin.hide();

        } else {
            JOptionPane.showMessageDialog(null, "User NAme or Password Invalid", "Pharamacy Sytem", JOptionPane.INFORMATION_MESSAGE);
            jPassword.setText("");
            jLogin.setText("");
            attempt+=1;
            
            if(attempt==3){
                JOptionPane.showMessageDialog(null, "You have tried 3 times", "Pharamacy Sytem", JOptionPane.ERROR_MESSAGE);
                 System.exit(0);
               
            }
        }

        {

        }
    }//GEN-LAST:event_jButloginActionPerformed

    private void jButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelActionPerformed
        jPassword.setText("");
        jLogin.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButCancelActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordActionPerformed

    private void jBPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPaymentActionPerformed

    private void jBConstantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConstantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConstantActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jBDocter.setEnabled(false);
        jBConstant.setEnabled(false);
        jBDocter.setEnabled(false);
        jBHelp.setEnabled(false);
        jBHospital.setEnabled(false);
        jBPatient.setEnabled(false);
        jBPayment.setEnabled(false);
        jBPharamcyffice.setEnabled(false);
        jBPharmacist.setEnabled(false);
        jBPharmacy.setEnabled(false);
        jBSpecialist.setEnabled(false);
        jBSurgery.setEnabled(false);
        jBGPAppointment.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jBPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPharmacyActionPerformed
  Pharmacy myPharmacy=new Pharmacy(); 
  myPharmacy.setVisible(true);
  // TODO add your handling code here:
    }//GEN-LAST:event_jBPharmacyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConstant;
    private javax.swing.JButton jBDocter;
    private javax.swing.JButton jBGPAppointment;
    private javax.swing.JButton jBHelp;
    private javax.swing.JButton jBHospital;
    private javax.swing.JButton jBPatient;
    private javax.swing.JButton jBPayment;
    private javax.swing.JButton jBPharamcyffice;
    private javax.swing.JButton jBPharmacist;
    private javax.swing.JButton jBPharmacy;
    private javax.swing.JButton jBSpecialist;
    private javax.swing.JButton jBSurgery;
    private javax.swing.JButton jButCancel;
    private javax.swing.JButton jButExit;
    private javax.swing.JButton jButlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
